#!/bin/bash

# Abort script in case any command fails
set -e

# General update
sudo apt update -y
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Update and upgrade OK"

# CMAKE
sudo apt install cmake -y
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> CMake OK"

# NUMACTL
sudo apt install numactl -y
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Numactl OK"

cd ..

# LLVM OpenMP
FILE=llvm-project/build-openmp/include/omp.h
if [[ -f "$FILE" ]];
then
    echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> LLVM already installed, skipping"
else
    git clone https://github.com/llvm/llvm-project.git
    cd llvm-project
    mkdir build-openmp
    cd build-openmp
    cmake ../openmp -G "Unix Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release  -DOPENMP_ENABLE_LIBOMPTARGET=OFF -DLIBOMP_OMPT_OPTIONAL=ON -DCMAKE_INSTALL_PREFIX=.
    make -j16
    make install
    cd
    echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> LLVM OK"
fi

# OpenBLAS
FILE=OpenBLAS/build/include/lapacke.h
if [[ -f "$FILE" ]];
then
    echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> OpenBLAS already installed, skipping"
else
    git clone https://github.com/xianyi/OpenBLAS.git
    cd OpenBLAS
    mkdir build
    make -j 12 USE_THREAD=1 NUM_BUFFERS=512 NUM_THREADS=512 CC=gcc CXX=g++
    make PREFIX=build/ install
    cd
    echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> OpenBLAS OK"
fi

sudo apt install libcpufreq-dev -y
sudo apt install cpufrequtils -y
sudo apt install libpapi-dev -y
sudo apt install papi-tools -y
sudo apt install libzmq3-dev -y
sudo apt install hwloc -y
sudo apt install acpi-support acpid acpi -y
cd TPM/

echo off | sudo tee /sys/devices/system/cpu/smt/control
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Disable hyperthreading OK"

echo 0 | sudo tee /proc/sys/kernel/perf_event_paranoid
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PAPI permissions OK"

echo "*** Done, now need to move from intel_pstate to ACPI!"
